### ISSUE TITLE
[BUG] Staticman comments error

### ISSUE THREAD

**Issue by VincentTam** [deadlydog/deadlydog.github.io#5]
![Screenshot from 2019-07-29 10-18-27](https://user-images.githubusercontent.com/5748535/62032566-4c2d1f80-b1ea-11e9-9291-1f1d5a145702.png)

See [my blog post about Staticman errors](https://vincenttam.gitlab.io/post/2018-12-25-staticman-repo-setup-errors/) for a list of errors and possible causes.  In your case, I've spotted out two errors.

1. Incorrect POST URL: see eduardoboucas/staticman#219 for info about Staticman v3 URL scheme
2. Unused reCAPTCHA parameters in Staticman config caused 500 Internal Server Error.  See my experiment in https://github.com/daattali/beautiful-jekyll/pull/514#issuecomment-508817895 for details.

**Comment by deadlydog** [comment]
Thanks for the info. With this info and others you provided I was able to get everything working :)
